stages:
  - deploy

deploy:
  stage: deploy
  script: 
  - docker container stop motive-backend
  - docker container prune -f
  - docker-compose build
  - docker run -d -p 8080:80 --name motive-backend backend-api
