stages:
  - build
  - deploy-frontend
  - deploy-backend
  
build:
  stage: build
  script:
  - sudo docker system prune -f
  - sudo docker-compose build

deploy-frontend:
  stage: deploy-frontend
  script: 
  - sudo docker container stop motive-frontend || true && sudo docker rm motive-frontend || true
  - sudo docker run -p 80:8082 -d --name motive-frontend frontend-web
  only:
  - dev@afr66/Motive


deploy-backend:
  stage: deploy-backend
  script: 
  - sudo docker container stop motive-backend || true && sudo docker rm motive-backend || true
  - sudo docker run -d -p 8080:80 --name motive-backend backend-api
  only:
  - dev@afr66/Motive
