stages:
  - deploy

deploy:
  stage: deploy
  script: 
  - sudo docker container stop motive-backend
  - sudo docker container prune -f
  - sudo docker-compose build
  - sudo docker run -d -p 8080:80 --name motive-backend backend-api
