stages:
  - deploy-frontend
  - deploy-backend

deploy-frontend:
  stage: deploy-frontend
  script: 
  - sudo docker container stop motive-frontend
  - sudo docker container prune -f
  - sudo docker-compose build
  - sudo docker run -p 80:8082 -d --name motive-frontend frontend-web
  only:
  - dev@afr66/Motive


deploy-backend:
  stage: deploy-backend
  script: 
  - sudo docker container stop motive-backend
  - sudo docker container prune -f
  - sudo docker-compose build
  - sudo docker run -d -p 8080:80 --name motive-backend backend-api
  only:
  - dev@afr66/Motive
